apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
  namespace: lab2
  labels:
    app: batch-job
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: worker
          image: busybox:1.36.1
          command: ["sh", "-lc"]
          args:
            - |
              echo "Elaboro il file di input...";
              cat /data/input.txt;
              echo "Lavoro completato"
