apiVersion: v1
kind: ServiceAccount
metadata:
  name: inspector
  namespace: lab7
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inspector
  namespace: lab7
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inspector
  namespace: lab7
subjects:
  - kind: ServiceAccount
    name: inspector
    namespace: lab7
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inspector
---
apiVersion: v1
kind: Pod
metadata:
  name: inspector
  namespace: lab7
  labels:
    app: inspector
spec:
  serviceAccountName: inspector
  restartPolicy: Always
  containers:
    - name: kubectl
      image: bitnami/kubectl:1.30.2
      command: ["sh", "-lc"]
      args:
        - |
          while true; do
            echo "[$(date)] === pods ===";
            kubectl get pods -n lab7 || echo "FAIL pods";
            echo "[$(date)] === svc ===";
            kubectl get svc -n lab7 || echo "FAIL svc";
            sleep 30;
          done
