apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: corso-demo
type: Opaque
stringData:
  postgres-user: catalog
  postgres-password: catalog
  postgres-db: catalogdb
  mongo-user: orders
  mongo-password: orders
  mongo-db: orderdb
