{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-secret
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ required "secret.apiToken e obbligatorio quando secret.enabled e true" .Values.secret.apiToken | quote }}
{{- end }}
