apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-probes
  namespace: lab1
  labels:
    app: web-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-probes
  template:
    metadata:
      labels:
        app: web-probes
    spec:
      containers:
        - name: web
          image: hashicorp/http-echo:1.0.0
          args:
            - "-listen=:8080"
            - "-text=ckad-probes-ok"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 5
