apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: lab1
  labels:
    app: web-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
        tier: backend
    spec:
      containers:
        - name: web
          image: hashicorp/http-echo:1.0.0
          args:
            - "-listen=:8080"
            - "-text=ckad-service-ok"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: lab1
spec:
  type: ClusterIP
  selector:
    app: web-svc
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 9090
