apiVersion: v1
kind: Pod
metadata:
  name: multi-init-demo
spec:
  initContainers:
    - name: init-download-config
      image: busybox
      command: ["sh", "-c", "echo 'config=ok' > /data/config.txt"]
      volumeMounts:
        - name: shared-data
          mountPath: /data

    - name: init-wait-service
      image: busybox
      command: ["sh", "-c", "until nslookup my-service; do echo waiting...; sleep 2; done"]

  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

  volumes:
    - name: shared-data
      emptyDir: {}