replicaCount: 1

image:
  repository: nginx
  # Se vuoto usa .Chart.AppVersion (definito in Chart.yaml).
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

config:
  logLevel: info
  featureFlags: basic

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
