apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa
  namespace: rbac-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader-sa
  namespace: rbac-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: rbac-lab
