apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-env
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  APP_MODE: {{ required "values.yaml: config.appMode e obbligatorio" .Values.config.appMode | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}
  FEATURE_FLAGS: {{ .Values.config.featureFlags | default "basic" | quote }}
